/**
 * Copyright Owliance © 2016 - 2017 ,All right reserved
 * <p>
 * Owliance PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
package com.owliance.owlink.vo;
// Generated 6 oct. 2016 17:08:50 by Hibernate Tools 3.4.0.CR1


import com.owliance.owlink.framework.entity.BaseVO;

import javax.persistence.*;
import java.util.Date;


/**
 * UsersVO generated by hbm2java.
 *
 * @author hbenizid
 * @see com.owliance.owlink.vo
 *
 * <p>
 * Created : 12 oct. 2016
 * <p>
 * Updated : 12 oct. 2016 by hbenizid (version 0.2.0-Alpha)
 * <p>
 * Updated : 23 nov. 2016 by hbenizid (version 0.3.1-Alpha)
 * @since 0.2.0-Alpha
 */
@Entity
@Table(name = "ALL_USERS_MUTIX", uniqueConstraints = @UniqueConstraint(columnNames = "USER_NOM"))
public class UsersVO extends BaseVO implements java.io.Serializable {

    /**
     * long.
     */
    private static final long serialVersionUID = -8277260890171491715L;

    /**
     * The id user.
     */
    private Long idUser;

    /**
     * The user nom.
     */
    private String userNom;

    /**
     * The user password.
     */
    private String userPassword;

    /**
     * The user dcse.
     */
    private String userDcse;

    /**
     * The user role.
     */
    private String userRole;

    /**
     * The user profil.
     */
    private String userProfil;

    /**
     * The user org.
     */
    private String userOrg;

    /**
     * The user comm.
     */
    private String userComm;

    /**
     * The user tel.
     */
    private String userTel;

    /**
     * The user date mod pwd.
     */
    private Date userDateModPwd;

    /**
     * The evt relance.
     */
    private Boolean evtRelance;

    /**
     * The evt relance market.
     */
    private Boolean evtRelanceMarket;

    /**
     * The evt relance market 2.
     */
    private Boolean evtRelanceMarket2;

    /**
     * The user last con.
     */
    private Date userLastCon;

    /**
     * The user flag con.
     */
    private Boolean userFlagCon;

    /**
     * The est admin.
     */
    private Boolean estAdmin;

    /**
     * The evt relance mark coll.
     */
    private Boolean evtRelanceMarkColl;

    /**
     * The evt relance mark ind.
     */
    private Boolean evtRelanceMarkInd;

    /**
     * The evt relance fam.
     */
    private Boolean evtRelanceFam;

    /**
     * The evt relance tie.
     */
    private Boolean evtRelanceTie;

    /**
     * The evt relance grp.
     */
    private Boolean evtRelanceGrp;

    /**
     * The user signature.
     */
    private String userSignature;

    /**
     * The user mail.
     */
    private Boolean userMail;

    /**
     * The user batch.
     */
    private Boolean userBatch;

    /**
     * 1 si utilisateur modèle, 0 sinon
     */
    private Boolean userModele;
    /**
     * Identifiant utilisateur modèle assigné
     */
    private Long idAssignedModele;
    /**
     * 1 si l'utilisateur à les habilitations prévoyance, 0 sinon
     */
    private Boolean habilitationPrev;

    /**
     * Date de dernière modification de l'utilisateur
     */
    private Date dateLastModif;

    /**
     * the address mail of user
     */
    private String userMailComment;

    /**
     * The user token.
     */
    private String userToken;

    /**
     * Indique si l'utilisateur peut se connecter à l'application (1 Non, 0 Oui)
     */
    private boolean userDisabled;

    /**
     * Instantiates a new all users .
     *
     * @param idUser the id user
     */
    public UsersVO(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * Instantiates a new all users .
     *
     * @param idUser  the id user
     * @param userNom the user nom
     */
    public UsersVO(Long idUser, String userNom) {
        this.idUser = idUser;
        this.userNom = userNom;
    }

    /**
     * Instantiates a new Users vo.
     *
     * @param idUser   the id user
     * @param userNom  the user nom
     * @param userComm the user comm
     */
    public UsersVO(Long idUser, String userNom, String userComm) {
        this.idUser = idUser;
        this.userNom = userNom;
        this.userComm = userComm;
    }

    /**
     * Instantiates a new Users vo.
     *
     * @param idUser           the id user
     * @param userNom          the user nom
     * @param idAssignedModele the id assigned modele
     */
    public UsersVO(Long idUser, String userNom, Long idAssignedModele) {
        this.idUser = idUser;
        this.userNom = userNom;
        this.idAssignedModele = idAssignedModele;
    }

    /**
     * Instantiates a new all users .
     *
     * @param userNom usernom
     */
    public UsersVO(String userNom) {
        this.userNom = userNom;
    }

    /**
     * Instantiates a new users VO.
     *
     * @param userNom      the user nom
     * @param userPassword the user password
     */
    public UsersVO(String userNom, String userPassword) {
        this.userNom = userNom;
        this.userPassword = userPassword;
    }

    /**
     * Gets the id user.
     *
     * @return the id user
     */
    @Id
    @Column(name = "ID_USER", unique = true, nullable = false, precision = 10, scale = 0)
    public Long getIdUser() {

        return this.idUser;
    }

    /**
     * Sets the id user.
     *
     * @param idUser the new id user
     */
    public void setIdUser(Long idUser) {

        this.idUser = idUser;
    }

    /**
     * Gets the user nom.
     *
     * @return the user nom
     */
    @Column(name = "USER_NOM", unique = true, nullable = false, length = 31)
    public String getUserNom() {

        return this.userNom;
    }

    /**
     * Sets the user nom.
     *
     * @param userNom the new user nom
     */
    public void setUserNom(String userNom) {

        this.userNom = userNom;
    }

    /**
     * Gets the user dcse.
     *
     * @return the user dcse
     */
    @Column(name = "USER_DCSE", length = 4000)
    public String getUserDcse() {

        return this.userDcse;
    }

    /**
     * Sets the user dcse.
     *
     * @param userDcse the new user dcse
     */
    public void setUserDcse(String userDcse) {

        this.userDcse = userDcse;
    }

    /**
     * Gets the user role.
     *
     * @return the user role
     */
    @Column(name = "USER_ROLE")
    public String getUserRole() {

        return this.userRole;
    }

    /**
     * Sets the user role.
     *
     * @param userRole the new user role
     */
    public void setUserRole(String userRole) {

        this.userRole = userRole;
    }

    /**
     * Gets the user profil.
     *
     * @return the user profil
     */
    @Column(name = "USER_PROFIL")
    public String getUserProfil() {

        return this.userProfil;
    }

    /**
     * Sets the user profil.
     *
     * @param userProfil the new user profil
     */
    public void setUserProfil(String userProfil) {

        this.userProfil = userProfil;
    }

    /**
     * Gets the user org.
     *
     * @return the user org
     */
    @Column(name = "USER_ORG")
    public String getUserOrg() {

        return this.userOrg;
    }

    /**
     * Sets the user org.
     *
     * @param userOrg the new user org
     */
    public void setUserOrg(String userOrg) {

        this.userOrg = userOrg;
    }

    /**
     * Gets the user comm.
     *
     * @return the user comm
     */
    @Column(name = "USER_COMM")
    public String getUserComm() {

        return this.userComm;
    }

    /**
     * Sets the user comm.
     *
     * @param userComm the new user comm
     */
    public void setUserComm(String userComm) {

        this.userComm = userComm;
    }

    /**
     * Gets the user tel.
     *
     * @return the user tel
     */
    @Column(name = "USER_TEL", length = 14)
    public String getUserTel() {

        return this.userTel;
    }

    /**
     * Sets the user tel.
     *
     * @param userTel the new user tel
     */
    public void setUserTel(String userTel) {

        this.userTel = userTel;
    }

    /**
     * Gets the user date mod pwd.
     *
     * @return the user date mod pwd
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "USER_DATE_MOD_PWD", length = 7)
    public Date getUserDateModPwd() {

        return this.userDateModPwd;
    }

    /**
     * Sets the user date mod pwd.
     *
     * @param userDateModPwd the new user date mod pwd
     */
    public void setUserDateModPwd(Date userDateModPwd) {

        this.userDateModPwd = userDateModPwd;
    }

    /**
     * Gets the evt relance.
     *
     * @return the evt relance
     */
    @Column(name = "EVT_RELANCE", precision = 1, scale = 0)
    public Boolean getEvtRelance() {

        return this.evtRelance;
    }

    /**
     * Sets the evt relance.
     *
     * @param evtRelance the new evt relance
     */
    public void setEvtRelance(Boolean evtRelance) {

        this.evtRelance = evtRelance;
    }

    /**
     * Gets the evt relance market.
     *
     * @return the evt relance market
     */
    @Column(name = "EVT_RELANCE_MARKET", precision = 1, scale = 0)
    public Boolean getEvtRelanceMarket() {

        return this.evtRelanceMarket;
    }

    /**
     * Sets the evt relance market.
     *
     * @param evtRelanceMarket the new evt relance market
     */
    public void setEvtRelanceMarket(Boolean evtRelanceMarket) {

        this.evtRelanceMarket = evtRelanceMarket;
    }

    /**
     * Gets the evt relance market 2.
     *
     * @return the evt relance market 2
     */
    @Column(name = "EVT_RELANCE_MARKET2", precision = 1, scale = 0)
    public Boolean getEvtRelanceMarket2() {

        return this.evtRelanceMarket2;
    }

    /**
     * Sets the evt relance market 2.
     *
     * @param evtRelanceMarket2 the new evt relance market 2
     */
    public void setEvtRelanceMarket2(Boolean evtRelanceMarket2) {

        this.evtRelanceMarket2 = evtRelanceMarket2;
    }

    /**
     * Gets the user last con.
     *
     * @return the user last con
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "USER_LAST_CON", length = 7)
    public Date getUserLastCon() {

        return this.userLastCon;
    }

    /**
     * Sets the user last con.
     *
     * @param userLastCon the new user last con
     */
    public void setUserLastCon(Date userLastCon) {

        this.userLastCon = userLastCon;
    }

    /**
     * Gets the user flag con.
     *
     * @return the user flag con
     */
    @Column(name = "USER_FLAG_CON", precision = 1, scale = 0)
    public Boolean getUserFlagCon() {

        return this.userFlagCon;
    }

    /**
     * Sets the user flag con.
     *
     * @param userFlagCon the new user flag con
     */
    public void setUserFlagCon(Boolean userFlagCon) {

        this.userFlagCon = userFlagCon;
    }

    /**
     * Gets the est admin.
     *
     * @return the est admin
     */
    @Column(name = "EST_ADMIN", precision = 1, scale = 0)
    public Boolean getEstAdmin() {

        return this.estAdmin;
    }

    /**
     * Sets the est admin.
     *
     * @param estAdmin the new est admin
     */
    public void setEstAdmin(Boolean estAdmin) {

        this.estAdmin = estAdmin;
    }

    /**
     * Gets the evt relance mark coll.
     *
     * @return the evt relance mark coll
     */
    @Column(name = "EVT_RELANCE_MARK_COLL", precision = 1, scale = 0)
    public Boolean getEvtRelanceMarkColl() {

        return this.evtRelanceMarkColl;
    }

    /**
     * Sets the evt relance mark coll.
     *
     * @param evtRelanceMarkColl the new evt relance mark coll
     */
    public void setEvtRelanceMarkColl(Boolean evtRelanceMarkColl) {

        this.evtRelanceMarkColl = evtRelanceMarkColl;
    }

    /**
     * Gets the evt relance mark ind.
     *
     * @return the evt relance mark ind
     */
    @Column(name = "EVT_RELANCE_MARK_IND", precision = 1, scale = 0)
    public Boolean getEvtRelanceMarkInd() {

        return this.evtRelanceMarkInd;
    }

    /**
     * Sets the evt relance mark ind.
     *
     * @param evtRelanceMarkInd the new evt relance mark ind
     */
    public void setEvtRelanceMarkInd(Boolean evtRelanceMarkInd) {

        this.evtRelanceMarkInd = evtRelanceMarkInd;
    }

    /**
     * Gets the evt relance fam.
     *
     * @return the evt relance fam
     */
    @Column(name = "EVT_RELANCE_FAM", precision = 1, scale = 0)
    public Boolean getEvtRelanceFam() {

        return this.evtRelanceFam;
    }

    /**
     * Sets the evt relance fam.
     *
     * @param evtRelanceFam the new evt relance fam
     */
    public void setEvtRelanceFam(Boolean evtRelanceFam) {

        this.evtRelanceFam = evtRelanceFam;
    }

    /**
     * Gets the evt relance tie.
     *
     * @return the evt relance tie
     */
    @Column(name = "EVT_RELANCE_TIE", precision = 1, scale = 0)
    public Boolean getEvtRelanceTie() {

        return this.evtRelanceTie;
    }

    /**
     * Sets the evt relance tie.
     *
     * @param evtRelanceTie the new evt relance tie
     */
    public void setEvtRelanceTie(Boolean evtRelanceTie) {

        this.evtRelanceTie = evtRelanceTie;
    }

    /**
     * Gets the evt relance grp.
     *
     * @return the evt relance grp
     */
    @Column(name = "EVT_RELANCE_GRP", precision = 1, scale = 0)
    public Boolean getEvtRelanceGrp() {

        return this.evtRelanceGrp;
    }

    /**
     * Sets the evt relance grp.
     *
     * @param evtRelanceGrp the new evt relance grp
     */
    public void setEvtRelanceGrp(Boolean evtRelanceGrp) {

        this.evtRelanceGrp = evtRelanceGrp;
    }

    /**
     * Gets the user signature.
     *
     * @return the user signature
     */
    @Column(name = "USER_SIGNATURE", length = 100)
    public String getUserSignature() {

        return this.userSignature;
    }

    /**
     * Sets the user signature.
     *
     * @param userSignature the new user signature
     */
    public void setUserSignature(String userSignature) {

        this.userSignature = userSignature;
    }

    /**
     * Gets the user mail.
     *
     * @return the user mail
     */
    @Column(name = "USER_MAIL", precision = 1, scale = 0)
    public Boolean getUserMail() {

        return this.userMail;
    }

    /**
     * Sets the user mail.
     *
     * @param userMail the new user mail
     */
    public void setUserMail(Boolean userMail) {

        this.userMail = userMail;
    }

    /**
     * Gets the user batch.
     *
     * @return the user batch
     */
    @Column(name = "USER_BATCH", precision = 1, scale = 0)
    public Boolean getUserBatch() {

        return this.userBatch;
    }

    /**
     * Sets the user batch.
     *
     * @param userBatch the new user batch
     */
    public void setUserBatch(Boolean userBatch) {

        this.userBatch = userBatch;
    }

    /**
     * Gets the user password.
     *
     * @return the userPassword
     */
    @Column(name = "USER_PWD", length = 2000)
    public String getUserPassword() {

        return userPassword;
    }

    /**
     * Sets the user password.
     *
     * @param userPassword the userPassword to set
     */
    public void setUserPassword(String userPassword) {

        this.userPassword = userPassword;
    }

    /**
     * Déterminer si l'utilisateur est un modèle ou non
     *
     * @return 1 si utilisateur modèle, 0 sinon
     */
    @Column(name = "USER_MODELE")
    public Boolean getUserModele() {
        return userModele;
    }

    /**
     * Marquer si l'utilisateur est modèle ou non
     *
     * @param userModele paramètre bollean si  true donc l'utilisateur est modèle
     */
    public void setUserModele(Boolean userModele) {
        this.userModele = userModele;
    }

    /**
     * Récupérer Identifiant utilisateur modèle
     *
     * @return Identifiant utilisateur modèle
     */
    @Column(name = "ID_USER_MODELE")
    public Long getIdAssignedModele() {
        return idAssignedModele;
    }

    /**
     * Assigner un utilisateur modele
     *
     * @param idAssignedModele id utilisateur modèle
     */
    public void setIdAssignedModele(Long idAssignedModele) {
        this.idAssignedModele = idAssignedModele;
    }

    /**
     * récupérer le paramétarge de l'utilisateur para rapport à la prévoyance
     *
     * @return 1 si l'utilisateur à les habilitations prévoyance, 0 sinon
     */
    @Column(name = "USER_HABIL_PREV")
    public Boolean getHabilitationPrev() {
        return habilitationPrev;
    }

    /**
     * Parmétrer l'utilisateur à la prévoyance
     *
     * @param habilitationPrev 1 si l'utilisateur à les habilitations prévoyance, 0 sinon
     */
    public void setHabilitationPrev(Boolean habilitationPrev) {
        this.habilitationPrev = habilitationPrev;
    }

    /**
     * Récupérer date dernière modification
     *
     * @return date dernière modification
     */
    @Temporal(TemporalType.DATE)
    @Column(name = "USER_MODIFICATION", length = 7)
    public Date getDateLastModif() {
        return dateLastModif;
    }

    /**
     * Définir date dernière modification
     *
     * @param dateLastModif Date de dernière modification de l'utilisateur
     */
    public void setDateLastModif(Date dateLastModif) {
        this.dateLastModif = dateLastModif;
    }

    /**
     * Gets user mail comment.
     *
     * @return the user mail comment
     */
    @Column(name = "USER_MAIL_COMM", length = 100)
    public String getUserMailComment() {
        return userMailComment;
    }

    /**
     * Sets user mail comment.
     *
     * @param userMailComment the user mail comment
     */
    public void setUserMailComment(String userMailComment) {
        this.userMailComment = userMailComment;
    }

    /**
     * Gets the user token.
     *
     * @return the userPassword
     */
    @Column(name = "USER_TOKEN", length = 32)
    public String getUserToken() {
        return userToken;
    }

    /**
     * Sets the user token.
     *
     * @param userToken the userToken to set
     */
    public void setUserToken(String userToken) {
        this.userToken = userToken;
    }

    /**
     * Retourne l'autorisation de connexion de l'utilisateur
     *
     * @return 0 si l'utilisateur peut se connecter à l'application 1 sinon
     */
    @Column(name = "USER_DISABLED")
    public boolean getUserDisabled() {
        return userDisabled;
    }

    /**
     * Modifie l'autorisation de connexion de l'utilisateur
     *
     * @param userDisabled 0 si l'utilisateur peut se connecter à l'application 1 sinon
     */
    public void setUserDisabled(boolean userDisabled) {
        this.userDisabled = userDisabled;
    }
}
